using System.Text.Json;
using Pdtf.Core;
using Pdtf.Core.Models;
using Xunit;

namespace Pdtf.Core.Tests;

/// <summary>
/// Cross-language test vector validation for C#/.NET bindings.
///
/// Consumes shared test vectors generated by the TypeScript reference
/// implementation and verifies that the C# bindings (via Rust FFI)
/// produce identical results.
/// </summary>
public class CrossLanguageTests
{
    private static readonly JsonElement Vectors;

    static CrossLanguageTests()
    {
        // Load test vectors from shared location
        var vectorsPath = Path.Combine(
            AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..",
            "test-vectors", "vectors.json"
        );
        var json = File.ReadAllText(Path.GetFullPath(vectorsPath));
        Vectors = JsonDocument.Parse(json).RootElement;
    }

    // ── Key Derivation ──────────────────────────────────────────────────

    [Fact]
    public void GenerateKeyPair_HasCorrectFormat()
    {
        var kp = PdtfCore.GenerateKeyPair();

        Assert.StartsWith("did:key:z6Mk", kp.Did);
        Assert.Equal(64, kp.PublicKeyHex.Length);  // 32 bytes hex
        Assert.Equal(64, kp.SecretKeyHex.Length);
    }

    [Fact]
    public void ResolveDidKey_MatchesTypeScript()
    {
        var did = Vectors.GetProperty("keys").GetProperty("did").GetString()!;
        var expected = Vectors.GetProperty("didDocument").GetProperty("expected");

        var docJson = PdtfCore.ResolveDidKey(did);
        var doc = JsonDocument.Parse(docJson).RootElement;

        Assert.Equal(
            expected.GetProperty("id").GetString(),
            doc.GetProperty("id").GetString()
        );

        var expectedVm = expected.GetProperty("verificationMethod")[0];
        var actualVm = doc.GetProperty("verificationMethod")[0];

        Assert.Equal(
            expectedVm.GetProperty("publicKeyMultibase").GetString(),
            actualVm.GetProperty("publicKeyMultibase").GetString()
        );
        Assert.Equal(did, actualVm.GetProperty("controller").GetString());
    }

    // ── Signing & Verification ──────────────────────────────────────────

    [Fact]
    public void SignAndVerify_Roundtrip()
    {
        var kp = PdtfCore.GenerateKeyPair();

        var vc = JsonSerializer.Serialize(new
        {
            @context = new[] {
                "https://www.w3.org/ns/credentials/v2",
                "https://propdata.org.uk/credentials/v2"
            },
            type = new[] { "VerifiableCredential", "PropertyDataCredential" },
            id = "urn:uuid:csharp-test-001",
            issuer = kp.Did,
            validFrom = "2026-01-01T00:00:00Z",
            credentialSubject = new
            {
                id = "urn:pdtf:uprn:100023336956",
                energyEfficiency = new { rating = "B", score = 85 }
            }
        });

        var signedJson = PdtfCore.SignCredential(vc, kp.SecretKeyHex);
        var signed = JsonDocument.Parse(signedJson).RootElement;

        // Must have a DataIntegrityProof
        var proof = signed.GetProperty("proof");
        Assert.Equal("DataIntegrityProof", proof.GetProperty("type").GetString());
        Assert.Equal("eddsa-jcs-2022", proof.GetProperty("cryptosuite").GetString());
        Assert.StartsWith("z", proof.GetProperty("proofValue").GetString());

        // Verify with correct key
        Assert.True(PdtfCore.VerifyProof(signedJson, kp.PublicKeyHex));
    }

    [Fact]
    public void VerifyTypeScriptSignedVCs()
    {
        foreach (var vv in Vectors.GetProperty("verification").EnumerateArray())
        {
            var name = vv.GetProperty("name").GetString()!;
            var vcJson = vv.GetProperty("vc").GetRawText();
            var publicKeyHex = vv.GetProperty("publicKeyHex").GetString()!;
            var expectedValid = vv.GetProperty("expectedValid").GetBoolean();

            var result = PdtfCore.VerifyProof(vcJson, publicKeyHex);
            Assert.Equal(expectedValid, result);
        }
    }

    [Fact]
    public void TamperedVC_FailsVerification()
    {
        var kp = PdtfCore.GenerateKeyPair();

        var vc = JsonSerializer.Serialize(new
        {
            @context = new[] {
                "https://www.w3.org/ns/credentials/v2",
                "https://propdata.org.uk/credentials/v2"
            },
            type = new[] { "VerifiableCredential", "PropertyDataCredential" },
            id = "urn:uuid:csharp-tamper-test",
            issuer = kp.Did,
            validFrom = "2026-01-01T00:00:00Z",
            credentialSubject = new
            {
                id = "urn:pdtf:uprn:100023336956",
                energyEfficiency = new { rating = "B", score = 85 }
            }
        });

        var signedJson = PdtfCore.SignCredential(vc, kp.SecretKeyHex);

        // Tamper with the subject
        var tampered = signedJson.Replace("\"score\":85", "\"score\":99");
        Assert.False(PdtfCore.VerifyProof(tampered, kp.PublicKeyHex));
    }

    [Fact]
    public void WrongKey_FailsVerification()
    {
        var kp1 = PdtfCore.GenerateKeyPair();
        var kp2 = PdtfCore.GenerateKeyPair();

        var vc = JsonSerializer.Serialize(new
        {
            @context = new[] {
                "https://www.w3.org/ns/credentials/v2",
                "https://propdata.org.uk/credentials/v2"
            },
            type = new[] { "VerifiableCredential", "PropertyDataCredential" },
            id = "urn:uuid:csharp-wrongkey-test",
            issuer = kp1.Did,
            validFrom = "2026-01-01T00:00:00Z",
            credentialSubject = new
            {
                id = "urn:pdtf:uprn:100023336956",
                energyEfficiency = new { rating = "A", score = 92 }
            }
        });

        var signedJson = PdtfCore.SignCredential(vc, kp1.SecretKeyHex);
        Assert.False(PdtfCore.VerifyProof(signedJson, kp2.PublicKeyHex));
    }

    // ── Status List ─────────────────────────────────────────────────────

    [Fact]
    public void EmptyStatusList_AllBitsFalse()
    {
        var size = Vectors.GetProperty("statusList").GetProperty("size").GetInt32();
        var bitstring = PdtfCore.CreateStatusList(size);

        foreach (var idx in new[] { 0, 1, 42, 100, size - 1 })
        {
            Assert.False(PdtfCore.CheckStatus(bitstring, idx),
                $"Empty list bit {idx} should be false");
        }
    }

    [Fact]
    public void DecodeTypeScriptBitstrings()
    {
        foreach (var op in Vectors.GetProperty("statusList").GetProperty("operations").EnumerateArray())
        {
            if (op.GetProperty("action").GetString() != "check") continue;

            var bitstring = op.GetProperty("bitstring").GetString()!;
            var index = op.GetProperty("index").GetInt32();
            var expected = op.GetProperty("expected").GetBoolean();

            var result = PdtfCore.CheckStatus(bitstring, index);
            Assert.Equal(expected, result);
        }
    }

    // ── TIR Path Matching ───────────────────────────────────────────────

    [Fact]
    public void TirPathMatching_MatchesTypeScript()
    {
        var issuerDid = Vectors.GetProperty("keys").GetProperty("did").GetString()!;

        foreach (var tv in Vectors.GetProperty("tirPathMatching").EnumerateArray())
        {
            var pattern = tv.GetProperty("pattern").GetString()!;
            var path = tv.GetProperty("path").GetString()!;
            var expected = tv.GetProperty("expected").GetBoolean();

            var registry = JsonSerializer.Serialize(new
            {
                version = "1.0.0",
                lastUpdated = "2026-01-01T00:00:00Z",
                issuers = new Dictionary<string, object>
                {
                    ["test-issuer"] = new
                    {
                        slug = "test-issuer",
                        name = "Test Issuer",
                        did = issuerDid,
                        trustLevel = "rootIssuer",
                        status = "active",
                        authorisedPaths = new[] { pattern },
                        validFrom = "2024-01-01T00:00:00Z"
                    }
                },
                userAccountProviders = new Dictionary<string, object>()
            });

            var result = PdtfCore.CheckTir(registry, issuerDid, new[] { path });
            Assert.Equal(expected, result.Trusted);
        }
    }

    // ── End-to-End Lifecycle ────────────────────────────────────────────

    [Fact]
    public void FullCredentialLifecycle()
    {
        // 1. Generate key
        var kp = PdtfCore.GenerateKeyPair();
        Assert.StartsWith("did:key:z6Mk", kp.Did);

        // 2. Resolve DID document
        var doc = JsonDocument.Parse(PdtfCore.ResolveDidKey(kp.Did)).RootElement;
        Assert.Equal(kp.Did, doc.GetProperty("id").GetString());

        // 3. Sign a VC
        var vc = JsonSerializer.Serialize(new
        {
            @context = new[] {
                "https://www.w3.org/ns/credentials/v2",
                "https://propdata.org.uk/credentials/v2"
            },
            type = new[] { "VerifiableCredential", "PropertyDataCredential" },
            id = "urn:uuid:csharp-e2e-test",
            issuer = kp.Did,
            validFrom = "2026-06-01T00:00:00Z",
            credentialSubject = new
            {
                id = "urn:pdtf:uprn:999999999999",
                floodRisk = new { zone = "1", risk = "low" }
            }
        });

        var signedJson = PdtfCore.SignCredential(vc, kp.SecretKeyHex);

        // 4. Verify — should pass
        Assert.True(PdtfCore.VerifyProof(signedJson, kp.PublicKeyHex));

        // 5. Tamper — should fail
        var tampered = signedJson.Replace("\"low\"", "\"high\"");
        Assert.False(PdtfCore.VerifyProof(tampered, kp.PublicKeyHex));

        // 6. Wrong key — should fail
        var kp2 = PdtfCore.GenerateKeyPair();
        Assert.False(PdtfCore.VerifyProof(signedJson, kp2.PublicKeyHex));

        // 7. Status list
        var bitstring = PdtfCore.CreateStatusList(131072);
        Assert.False(PdtfCore.CheckStatus(bitstring, 42));
    }
}
