//! Cross-language test vector validation.
//!
//! Consumes vectors generated by the TypeScript reference implementation
//! to prove byte-level interoperability between TS and Rust.
//!
//! Vectors file: test-vectors/vectors.json (generated by pdtf-core-ts)

use pdtf_core::keys::ed25519::{derive_did_key, did_key_to_public_key, public_key_to_multibase};
use pdtf_core::signer::proof::verify_proof;
use pdtf_core::status::bitstring::{
    create_status_list, decode_status_list, get_bit, set_bit,
};
use pdtf_core::tir::path_match::path_matches;
use pdtf_core::types::VerifiableCredential;
use serde::Deserialize;
use serde_json::Value;

const VECTORS_JSON: &str = include_str!("../../../test-vectors/vectors.json");

// ─── Vector types ───────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct Vectors {
    keys: KeyEntry,
    signing: Vec<SigningVector>,
    verification: Vec<VerificationVector>,
    #[serde(rename = "statusList")]
    status_list: StatusListVectors,
    #[serde(rename = "tirPathMatching")]
    tir_path_matching: Vec<TirPathVector>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct KeyEntry {
    seed: String,
    #[serde(rename = "publicKeyHex")]
    public_key_hex: String,
    #[serde(rename = "secretKeyHex")]
    secret_key_hex: String,
    did: String,
    #[serde(rename = "publicKeyMultibase")]
    public_key_multibase: String,
}

#[derive(Deserialize)]
struct SigningVector {
    name: String,
    #[serde(rename = "unsignedVc")]
    unsigned_vc: Value,
    #[serde(rename = "signedVc")]
    signed_vc: Value,
    #[serde(rename = "proofValue")]
    proof_value: String,
}

#[derive(Deserialize)]
struct VerificationVector {
    name: String,
    vc: Value,
    #[serde(rename = "publicKeyHex")]
    public_key_hex: String,
    #[serde(rename = "expectedValid")]
    expected_valid: bool,
}

#[derive(Deserialize)]
struct StatusListVectors {
    size: usize,
    #[serde(rename = "emptyBitstring")]
    empty_bitstring: String,
    operations: Vec<StatusOp>,
}

#[derive(Deserialize)]
struct StatusOp {
    action: String,
    index: usize,
    #[serde(rename = "bitstringAfter")]
    bitstring_after: Option<String>,
    bitstring: Option<String>,
    expected: Option<bool>,
}

#[derive(Deserialize)]
struct TirPathVector {
    pattern: String,
    path: String,
    expected: bool,
}

fn load_vectors() -> Vectors {
    serde_json::from_str(VECTORS_JSON).expect("Failed to parse test vectors")
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

// ─── Key Derivation ─────────────────────────────────────────────────────────

#[test]
fn crosslang_key_derivation() {
    let v = load_vectors();
    let pk_bytes = hex_to_bytes(&v.keys.public_key_hex);

    let did = derive_did_key(&pk_bytes).expect("derive_did_key");
    assert_eq!(did, v.keys.did, "DID mismatch");

    let multibase = public_key_to_multibase(&pk_bytes).expect("multibase");
    assert_eq!(multibase, v.keys.public_key_multibase, "Multibase mismatch");

    let recovered = did_key_to_public_key(&did).expect("roundtrip");
    assert_eq!(recovered.as_slice(), pk_bytes.as_slice(), "Round-trip failed");
}

// ─── Signing ────────────────────────────────────────────────────────────────
// Rust signs the same unsigned VCs with the same key and timestamp.
// The proof values MUST match exactly (same JCS, same Ed25519 signature).

#[test]
fn crosslang_signing_produces_identical_proofs() {
    let v = load_vectors();
    let seed_bytes = hex_to_bytes(&v.keys.secret_key_hex);
    let signing_key =
        ed25519_dalek::SigningKey::from_bytes(seed_bytes.as_slice().try_into().unwrap());

    for sv in &v.signing {
        // Extract the created timestamp and verificationMethod from the TS-signed VC
        let ts_proof = sv.signed_vc.get("proof").expect("signed VC must have proof");
        let created = ts_proof.get("created").unwrap().as_str().unwrap();
        let vm = ts_proof.get("verificationMethod").unwrap().as_str().unwrap();

        // Build proof options matching TS
        let proof_options = serde_json::json!({
            "type": "DataIntegrityProof",
            "cryptosuite": "eddsa-jcs-2022",
            "verificationMethod": vm,
            "proofPurpose": "assertionMethod",
            "created": created,
        });

        let proof_options_canonical =
            json_canon::to_string(&proof_options).expect("JCS proof options");
        let proof_options_hash =
            <sha2::Sha256 as sha2::Digest>::digest(proof_options_canonical.as_bytes());

        let doc_canonical = json_canon::to_string(&sv.unsigned_vc).expect("JCS document");
        let document_hash =
            <sha2::Sha256 as sha2::Digest>::digest(doc_canonical.as_bytes());

        let mut combined = Vec::with_capacity(64);
        combined.extend_from_slice(&proof_options_hash);
        combined.extend_from_slice(&document_hash);

        use ed25519_dalek::Signer;
        let signature = signing_key.sign(&combined);
        let proof_value = format!("z{}", bs58::encode(signature.to_bytes()).into_string());

        assert_eq!(
            proof_value, sv.proof_value,
            "Proof value mismatch for '{}'",
            sv.name
        );
    }
}

// ─── Verification ───────────────────────────────────────────────────────────
// Rust verifies VCs that were signed by TypeScript.

#[test]
fn crosslang_verification() {
    let v = load_vectors();

    for vv in &v.verification {
        let vc: VerifiableCredential =
            serde_json::from_value(vv.vc.clone()).unwrap_or_else(|e| {
                panic!("Parse VC '{}': {}", vv.name, e);
            });
        let pk_bytes = hex_to_bytes(&vv.public_key_hex);
        let pk: [u8; 32] = pk_bytes.as_slice().try_into().unwrap();

        let valid = verify_proof(&vc, &pk);
        assert_eq!(
            valid, vv.expected_valid,
            "Verification '{}': expected {}, got {}",
            vv.name, vv.expected_valid, valid
        );
    }
}

// ─── Status List ────────────────────────────────────────────────────────────
// Note: gzip implementations may produce different byte sequences for the same
// logical content, so we test logical equivalence (decode → check bits) rather
// than exact bitstring equality.

#[test]
fn crosslang_status_list_empty_roundtrip() {
    let v = load_vectors();

    // Decode TS-produced empty bitstring
    let ts_decoded = decode_status_list(&v.status_list.empty_bitstring)
        .expect("decode TS empty bitstring");
    assert_eq!(ts_decoded.len(), v.status_list.size / 8, "Size mismatch");

    // All bits should be 0
    for i in [0, 1, 42, 1000, v.status_list.size - 1] {
        assert_eq!(
            get_bit(&ts_decoded, i).unwrap(),
            false,
            "Empty list bit {} should be false",
            i
        );
    }

    // Rust-produced empty list should also decode to all zeros
    let rs_list = create_status_list(v.status_list.size).expect("create");
    assert_eq!(rs_list, ts_decoded, "Empty list bytes differ");
}

#[test]
fn crosslang_status_list_operations() {
    let v = load_vectors();

    // Track which bits have been set (for incremental verification)
    let mut set_indices: Vec<usize> = Vec::new();

    for op in &v.status_list.operations {
        match op.action.as_str() {
            "set" => {
                set_indices.push(op.index);

                // Decode the TS bitstring-after and verify the expected bits
                let ts_decoded = decode_status_list(
                    op.bitstring_after.as_ref().expect("set needs bitstringAfter"),
                )
                .expect("decode");

                // All set indices should be true
                for &idx in &set_indices {
                    assert!(
                        get_bit(&ts_decoded, idx).unwrap(),
                        "After set({}): bit {} should be true",
                        op.index,
                        idx
                    );
                }

                // A bit we haven't set should be false
                let unset = (0..v.status_list.size)
                    .find(|i| !set_indices.contains(i))
                    .unwrap();
                assert!(
                    !get_bit(&ts_decoded, unset).unwrap(),
                    "Bit {} should still be false",
                    unset
                );

                // Rust should produce identical decoded bytes
                let mut rs_list = create_status_list(v.status_list.size).unwrap();
                for &idx in &set_indices {
                    set_bit(&mut rs_list, idx).unwrap();
                }
                assert_eq!(
                    rs_list, ts_decoded,
                    "Rust and TS decoded bytes differ after set({})",
                    op.index
                );
            }
            "check" => {
                let bitstring = op.bitstring.as_ref().expect("check needs bitstring");
                let decoded = decode_status_list(bitstring).expect("decode");
                let actual = get_bit(&decoded, op.index).expect("get_bit");
                let expected = op.expected.expect("check needs expected");
                assert_eq!(
                    actual, expected,
                    "Status check at index {}: expected {}, got {}",
                    op.index, expected, actual
                );
            }
            other => panic!("Unknown operation: {other}"),
        }
    }
}

// ─── TIR Path Matching ─────────────────────────────────────────────────────

#[test]
fn crosslang_tir_path_matching() {
    let v = load_vectors();

    for tv in &v.tir_path_matching {
        let result = path_matches(&tv.pattern, &tv.path);
        assert_eq!(
            result, tv.expected,
            "pattern='{}' path='{}': expected {}, got {}",
            tv.pattern, tv.path, tv.expected, result
        );
    }
}
