//! Cross-language test vector validation.
//!
//! Consumes deterministic test vectors generated by the TypeScript
//! reference implementation (@pdtf/core) and validates that the Rust
//! implementation produces identical results.
//!
//! Vectors file: ../../test-vectors/vectors.json (relative to workspace root)

use ed25519_dalek::{Signer, SigningKey};
use pdtf_core::did::did_key::resolve_did_key;
use pdtf_core::keys::ed25519::{derive_did_key, public_key_to_multibase};
use pdtf_core::signer::proof::verify_proof;
use pdtf_core::status::bitstring::{
    create_status_list, decode_status_list, encode_status_list, get_bit, set_bit,
};
use pdtf_core::tir::path_match::path_matches;
use pdtf_core::types::VerifiableCredential;
use serde_json::Value;
use sha2::{Digest, Sha256};

/// Load vectors.json at compile time.
const VECTORS_JSON: &str = include_str!("../../../test-vectors/vectors.json");

fn vectors() -> Value {
    serde_json::from_str(VECTORS_JSON).expect("Failed to parse vectors.json")
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

// ─── Keys ───────────────────────────────────────────────────────────────────

#[test]
fn test_keys_derive_did_from_seed() {
    let v = vectors();
    let keys = &v["keys"];

    let seed_hex = keys["seed"].as_str().unwrap();
    let expected_pk_hex = keys["publicKeyHex"].as_str().unwrap();
    let expected_did = keys["did"].as_str().unwrap();
    let expected_multibase = keys["publicKeyMultibase"].as_str().unwrap();

    // Derive public key from seed using ed25519-dalek
    let seed_bytes = hex_to_bytes(seed_hex);
    let signing_key = SigningKey::from_bytes(seed_bytes.as_slice().try_into().unwrap());
    let verifying_key = signing_key.verifying_key();

    // Check public key matches
    let pk_hex: String = verifying_key
        .as_bytes()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    assert_eq!(pk_hex, expected_pk_hex, "Public key mismatch");

    // Check did:key matches
    let did = derive_did_key(verifying_key.as_bytes()).unwrap();
    assert_eq!(did, expected_did, "did:key mismatch");

    // Check multibase matches
    let multibase = public_key_to_multibase(verifying_key.as_bytes()).unwrap();
    assert_eq!(multibase, expected_multibase, "multibase mismatch");
}

// ─── DID Document ───────────────────────────────────────────────────────────

#[test]
fn test_did_document_resolution() {
    let v = vectors();
    let dd = &v["didDocument"];

    let input_did = dd["input"].as_str().unwrap();
    let expected = &dd["expected"];

    let doc = resolve_did_key(input_did).unwrap();
    let doc_json = serde_json::to_value(&doc).unwrap();

    // Compare id
    assert_eq!(doc_json["id"], expected["id"], "DID document id mismatch");

    // Compare @context
    assert_eq!(
        doc_json["@context"], expected["@context"],
        "DID document @context mismatch"
    );

    // Compare verification method
    let vm_actual = &doc_json["verificationMethod"][0];
    let vm_expected = &expected["verificationMethod"][0];
    assert_eq!(vm_actual["id"], vm_expected["id"], "VM id mismatch");
    assert_eq!(
        vm_actual["type"], vm_expected["type"],
        "VM type mismatch"
    );
    assert_eq!(
        vm_actual["controller"], vm_expected["controller"],
        "VM controller mismatch"
    );
    assert_eq!(
        vm_actual["publicKeyMultibase"], vm_expected["publicKeyMultibase"],
        "VM publicKeyMultibase mismatch"
    );

    // Compare authentication and assertionMethod
    assert_eq!(
        doc_json["authentication"], expected["authentication"],
        "authentication mismatch"
    );
    assert_eq!(
        doc_json["assertionMethod"], expected["assertionMethod"],
        "assertionMethod mismatch"
    );
}

// ─── Signing ────────────────────────────────────────────────────────────────

#[test]
fn test_signing_vectors() {
    let v = vectors();
    let keys = &v["keys"];
    let seed_hex = keys["seed"].as_str().unwrap();
    let seed_bytes = hex_to_bytes(seed_hex);
    let signing_key = SigningKey::from_bytes(seed_bytes.as_slice().try_into().unwrap());

    let did = keys["did"].as_str().unwrap();
    let multibase = keys["publicKeyMultibase"].as_str().unwrap();
    let verification_method = format!("{did}#{multibase}");

    let signing_vectors = v["signing"].as_array().unwrap();

    for sv in signing_vectors {
        let name = sv["name"].as_str().unwrap();
        let unsigned_vc = &sv["unsignedVc"];
        let expected_proof_value = sv["proofValue"].as_str().unwrap();

        // Reconstruct the signing process (eddsa-jcs-2022)
        let created = unsigned_vc["validFrom"].as_str().unwrap();

        let proof_options = serde_json::json!({
            "type": "DataIntegrityProof",
            "cryptosuite": "eddsa-jcs-2022",
            "verificationMethod": verification_method,
            "proofPurpose": "assertionMethod",
            "created": created,
        });

        // Hash proof options (JCS-canonicalized)
        let proof_options_canonical = json_canon::to_string(&proof_options).unwrap();
        let proof_options_hash = Sha256::digest(proof_options_canonical.as_bytes());

        // Hash document (JCS-canonicalized, without proof)
        let doc_canonical = json_canon::to_string(unsigned_vc).unwrap();
        let document_hash = Sha256::digest(doc_canonical.as_bytes());

        // Concatenate hashes
        let mut combined = Vec::with_capacity(64);
        combined.extend_from_slice(&proof_options_hash);
        combined.extend_from_slice(&document_hash);

        // Sign
        let signature = signing_key.sign(&combined);
        let proof_value = format!("z{}", bs58::encode(signature.to_bytes()).into_string());

        assert_eq!(
            proof_value, expected_proof_value,
            "Signing vector '{name}': proofValue mismatch"
        );
    }
}

// ─── Verification ───────────────────────────────────────────────────────────

#[test]
fn test_verification_vectors() {
    let v = vectors();
    let verification_vectors = v["verification"].as_array().unwrap();

    for vv in verification_vectors {
        let name = vv["name"].as_str().unwrap();
        let vc_json = &vv["vc"];
        let pk_hex = vv["publicKeyHex"].as_str().unwrap();
        let expected_valid = vv["expectedValid"].as_bool().unwrap();

        let pk_bytes = hex_to_bytes(pk_hex);
        let pk: [u8; 32] = pk_bytes.as_slice().try_into().unwrap();

        // Parse VC through serde
        let vc: VerifiableCredential =
            serde_json::from_value(vc_json.clone()).unwrap_or_else(|e| {
                panic!("Failed to parse VC for vector '{name}': {e}")
            });

        let valid = verify_proof(&vc, &pk);
        assert_eq!(
            valid, expected_valid,
            "Verification vector '{name}': expected {expected_valid}, got {valid}"
        );
    }
}

// ─── Status List ────────────────────────────────────────────────────────────

#[test]
fn test_status_list_vectors() {
    let v = vectors();
    let sl = &v["statusList"];
    let size = sl["size"].as_u64().unwrap() as usize;
    let expected_empty = sl["emptyBitstring"].as_str().unwrap();

    // Test empty list encoding
    let empty_list = create_status_list(size).unwrap();
    let _empty_encoded = encode_status_list(&empty_list).unwrap();

    // Decode both and compare raw bitstrings (gzip encoding may differ)
    let expected_empty_raw = decode_status_list(expected_empty).unwrap();
    assert_eq!(
        empty_list, expected_empty_raw,
        "Empty status list raw bitstring mismatch"
    );

    // Process operations sequentially
    let mut list = create_status_list(size).unwrap();
    let operations = sl["operations"].as_array().unwrap();

    for op in operations {
        let action = op["action"].as_str().unwrap();
        let index = op["index"].as_u64().unwrap() as usize;

        match action {
            "set" => {
                set_bit(&mut list, index).unwrap();
                let expected_after = op["bitstringAfter"].as_str().unwrap();

                // Decode expected and compare raw bitstrings
                let expected_raw = decode_status_list(expected_after).unwrap();
                assert_eq!(
                    list.as_slice(),
                    expected_raw.as_slice(),
                    "Status list mismatch after set({index})"
                );
            }
            "check" => {
                let bitstring_encoded = op["bitstring"].as_str().unwrap();
                let expected = op["expected"].as_bool().unwrap();

                let bitstring = decode_status_list(bitstring_encoded).unwrap();
                let actual = get_bit(&bitstring, index).unwrap();
                assert_eq!(
                    actual, expected,
                    "Status list check({index}): expected {expected}, got {actual}"
                );
            }
            other => panic!("Unknown status list action: {other}"),
        }
    }
}

// ─── TIR Path Matching ─────────────────────────────────────────────────────

#[test]
fn test_tir_path_matching_vectors() {
    let v = vectors();
    let tir_vectors = v["tirPathMatching"].as_array().unwrap();

    for tv in tir_vectors {
        let pattern = tv["pattern"].as_str().unwrap();
        let path = tv["path"].as_str().unwrap();
        let expected = tv["expected"].as_bool().unwrap();

        let actual = path_matches(pattern, path);
        assert_eq!(
            actual, expected,
            "TIR path match: pattern='{pattern}', path='{path}': expected {expected}, got {actual}"
        );
    }
}
